all: trexplayer.exe

trexplayer.exe: rensya_window.cpp debug_window.cpp main.cpp judger.cpp ai.cpp send_key.cpp
	g++ rensya_window.cpp debug_window.cpp main.cpp judger.cpp ai.cpp send_key.cpp -o trexplayer.exe -lGdi32 -Wall

